services:
  - type: web
    env: static
    name: saas-web
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://diplomatic-simplicity-production-70e0.up.railway.app/v1"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
